# Guidelines for StyleGAN2 config
# Don't change cfgs except for the explained below as comment.
# Changing other cfgs will cause it to deviate from original StyleGAN paper settings.
# g_cond_mtd can be changed btw ["W/O", "cAdaIN"]
# d_cond_mtd can be changed btw ["W/O", "AC", "PD", "MH", "MD", "2C", "D2DCE", "SPD"]
# z_dim, w_dim should be fixed to 512 regardless of image size.
# apply_g_ema should be true for stable results.
# apply_r1_reg should be true.
# g_reg_interval, d_reg_interval is fixed to 4, 16 regardless of image size.
# pl_reg is disabled only for cifar10. 
# d_architecture is 'orig' for cifar10.
# style_mixing_p should be 0.9 for all settings except for cifar10 (0)
# for total_step, batch_size, d_epilogue_mbstd_group_size, g/d_lr, r1_lambda, g_ema_kimg
# g_ema_rampup, mapping_network, check StyleGAN2 section in src/config.py

DATA:
  name: "HE"
  img_size: 224
  num_classes: 9
MODEL:
  backbone: "advgan"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
LOSS:
  adv_loss: "logistic"
  #adv_loss: "wasserstein"
  #apply_wc: True
  #wc_bound: 0.01
  #adv_loss: "hinge"
  #cond_lambda: 0.5
  #m_p: 0.98
  #temperature: 0.5
OPTIMIZATION:
  # These values will be slightly changed if lazy regularization is applied.
  g_lr: 0.0025
  d_lr: 0.0025
  beta1: 0
  beta2: 0.99
  g_updates_per_step: 1
  d_updates_per_step: 1
  total_steps: 400000
  batch_size: 32
